config/routes.rb
Nerdnews::Application.routes.draw do
  match "under_construction", :to => redirect('/')

  root :to => "stories#index"

  get "/faq" => "static_pages#faq", as: "static_pages_faq"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  match '/auth/:provider/callback' => 'identities#create'
  match '/auth/failure' => 'identities#failure'

  resources :identities, :only => [:index, :create, :destroy] do
    collection do
      get 'signup'
    end
  end

  resources :activity_logs
  resources :ratings
  resources :password_resets
  resources :pages
  resources :tags
  resources :mypage, only: :index
  resources :announcements do
    get :hide, on: :member
  end

  get "/login" => "sessions#new", as: "new_session"
  post "/login" => "sessions#create", as: "sessions"
  delete "/logout" => "sessions#destroy", as: "session"

  resources :users, path_names: { new: 'sign_up' } do
    get 'posts', on: :member
    get 'comments', on: :member
    get 'favorites', on: :member
    get 'activity_logs', on: :member
    post 'add_to_favorites', on: :member
    resources :messages, except: [:edit, :update, :show], path_names: { new: 'new' }
  end

  resources :stories do
    resources :votes, :defaults => { :voteable => 'stories' }
    resources :comments do
      resources :votes, :defaults => { :voteable => 'comments' }
    end
    get 'unpublished', :on => :collection
    put 'publish', :on => :member
    get 'recent', on: :collection
  end

  get "/:permalink" => "pages#show", as: "page_by_permalink"

  namespace :admin do
    get '', to: 'dashboard#index'
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_paranoid

  include Rakismet::Model

  HIDE_THRESHOLD = -8

  scope :approved, where(approved: true)

  has_many :votes, as: :voteable
  belongs_to :story, counter_cache: true
  belongs_to :user, counter_cache: true

  attr_accessible :content, :name, :email, :website, :user_id, :parent_id
  rakismet_attrs author: :name, author_email: :email, author_url: :website

  before_validation :smart_add_url_protocol
  before_create :is_spam?

  validates :name, :content, :user_ip, :user_agent, :referrer, presence: true
  validates :email, email_format: true, presence: true
  validates :website, allow_blank: true, uri: true

  has_ancestry

  def user_voted?(user)
    !self.votes.where("user_id = ?", user).blank?
  end

  # check if the parent story is approved
  def parent_approved?
    self.story.approved?
  end

  def add_user_requests_data=(request)
    self.user_ip = request.remote_ip
    self.user_agent = request.env['HTTP_USER_AGENT']
    self.referrer = request.env['HTTP_REFERER']
  end

  def mark_as_spam
    self.spam!
    self.update_attribute :approved, false
  end

  def mark_as_not_spam
    self.ham!
    self.update_attribute approved: true
  end

  def votes_sum
    positive_votes_count - negative_votes_count
  end

  protected
  # Searches through recent comments and mark them to hide if
  # too much negative rating is submitted for them
  def self.hide_negative_comments
    recent_comments = where(created_at: (Time.now.midnight - 1.day)..Time.now.midnight)
    recent_comments.each do |comment|
      comment.update_attribute :approved, false if comment.total_point < Comment::HIDE_THRESHOLD
      comment.index!
    end
  end

  private

    def smart_add_url_protocol
      if self.website.present?
        unless self.website[/^https?:\/\//]
          self.website = 'http://' + self.website
        end
      end
    end

    def is_spam?
      self.approved = !self.spam?
      true # Send True to not prevent from saving record
    end
end

app/controllers/comments_controller.rb
# encoding: utf-8

class CommentsController < ApplicationController
  load_and_authorize_resource
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @story = Story.find(params[:story_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new(parent_id: params[:parent_id])
    @story = Story.find(params[:story_id])

    respond_to do |format|
      format.html # new.html.erb
      format.js
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
    @story = Story.find(params[:story_id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @story = Story.find(params[:story_id])
    @comment = @story.comments.build(params[:comment])
    @comment.add_user_requests_data = request
    @comments = @story.comments.arrange(order: :created_at)

    respond_to do |format|
      if @comment.save

        record_activity %Q(دیدگاهی جدید برای خبر #{view_context.link_to @story.title.truncate(40), story_path(@story, :anchor => "comment_#{@comment.id}")} ایجاد کرد)

        UserMailer.delay.comment_reply(@comment.id) unless @comment.parent.nil?
        rate_user(current_user, 1) if current_user.present?
        format.html { redirect_to @story, notice: t('controllers.comments.create.flash.success') }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render template: "stories/show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])
    @story = Story.find(params[:story_id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        record_activity %Q(دیدگاه در خبر #{view_context.link_to @story.title.truncate(40), story_path(@story, :anchor => "comment_#{@comment.id}")} را ویرایش کرد)

        format.html { redirect_to story_path(@comment.story),
          notice: t('controllers.comments.update.flash.success') }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    record_activity %Q(دیدگاه در خبر #{view_context.link_to @story.title.truncate(40), story_path(@story, :anchor => "comment_#{@comment.id}")} را حذف کرد)

    respond_to do |format|
      format.html { redirect_to story_path(@comment.story) }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def find_peoper_class(comment)
    if can? :update, comment
      'btn-group btn-group-vertical'
    end
  end

  def hide_comment?(comment)
    if comment.total_point < Comment::HIDE_THRESHOLD
      return true
    end
    return false
  end
end

app/views/comments/_comment.html.erb
<!-- cache status of Story -->
<% status = hide_comment?(comment) %>
<div class="comment <%= "grey-out" if status %>" id="comment_<%= comment.id %>">
  <div>
    <%= image_tag avatar_url(comment, 32), class: 'pull-right img-polaroid clearfix' %>
  </div>

  <div class="main">

    <span class='owner'>

      <% if comment.user_id.nil? %>
        <%= comment.name %>
      <% else %>
        <%= link_to comment.name, user_path(comment.user) %>
      <% end %>

      <% if comment.parent.present? %>
        <small class='muted'>
        <i class='icon-arrow-left'></i>
        در جواب
        <%= comment.parent.name %>
      </small>
      <% end %>

    </span>

    <h5 class="muted">
      <small>
        <span>
          <i class='icon-calendar'></i>
            <%= link_to story_path(comment.story, :anchor => "comment_#{comment.id}") do %>
            <%= time_ago_in_words(comment.created_at).to_farsi + ' قبل' %>
            <% end %>
        </span>
        <% if comment.website.present? %>
          <i class='icon-link'></i>
          <%= link_to 'وب‌سایت', comment.website %>
        <% end %>
      </small>
    </h5>

    <div>
      <p>
        <%= sanitize(RedCloth.new(comment.content, [:filter_html, :filter_styles]).to_html) %>
      </p>
    </div>

    <div class='row'>
      <% if can? :create, Vote %>
        <div id='voting-buttons-<%= comment.id %>' class='span1 pull-right'>
          <%= render 'comments/voting_buttons', comment: comment %>
        </div>
      <% end %>
      <!-- <h5 class="muted"> -->
        <div class='span3 thumbs-up-list' id='thumbs-up-list-<%= comment.id %>'>
          <ul>
            <% Rating.positive('comments').each do |rating| %>
              <li class='icon-hand-left'>
                <%= link_to rating.name, story_comment_votes_path(comment.story, comment, rating_id: rating, positive: true),
                  method: :post, remote: true %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class='span3 thumbs-down-list' id='thumbs-down-list-<%= comment.id %>'>
          <ul>
            <% Rating.negative('comments').each do |rating| %>
              <li class='icon-hand-left'>
                <%= link_to rating.name, story_comment_votes_path(comment.story, comment, rating_id: rating), method: :post, remote: true %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class='pull-left'>
          <small>
            <%= link_to t('.reply', :default => t("helpers.links.reply")),
            new_story_comment_path(comment.story, parent_id: comment), remote: true %>

            <% if can? :update, comment %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_story_comment_path(comment.story, comment) %>
            <% end %>

            <% if can? :destroy, comment %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                [comment.story, comment], :method => :delete,
                :confirm => t('.confirm', :default => t("helpers.links.confirm",
                  :default => 'Are you sure?')) %>
            <% end %>
          </small>
        </div>
    </div>

  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for [@story, @comment], :html => { :class => '' } do |f| %>
<div class='comment-form'>

  <div class='row'>
    <div class='span6'>

      <%= f.input :parent_id, as: :hidden %>
      <%= f.input :content, label: false, placeholder: "#{t('.write_your_comment')}", input_html: {rows: 3, class: "span6"} %>

    </div>
  </div>

  <div class='row'>
    <% if current_user.nil? %>

      <div class='span4'>

      <%= f.input :name, label: false, input_html: {class: 'span4'}, placeholder: "*#{t('activerecord.attributes.comment.name')}" %>

      <%= f.input :email, label: false, input_html: {class: 'span4'}, placeholder: "*#{t('activerecord.attributes.comment.email')}" %>

      <%= f.input :website, label: false, input_html: {class: 'span4'}, placeholder: "#{t('activerecord.attributes.comment.website')}" %>

      </div>

      <div class='span2' style='text-align: center'>
        <%= image_tag 'nobody.png', class: 'img-polaroid' %>
        <p><b><%=t '.You!' %></b></p>
        <p>
          <%= link_to t('shared.header.login'), new_session_path %>
          /
          <%= link_to t('shared.header.register'), new_user_path %>
        </p>
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>

    <% elsif ["edit", "update"].include?(params[:action]) %>
      <div class='span4'>

        <%= f.input :name, readonly: true, label: false, input_html: {class: 'span4'}, placeholder: "*#{t('activerecord.attributes.comment.name')}" %>

        <%= f.input :email, readonly: true, label: false, input_html: {class: 'span4'}, placeholder: "*#{t('activerecord.attributes.comment.email')}" %>

        <%= f.input :website, readonly: true, label: false, input_html: {class: 'span4'}, placeholder: "#{t('activerecord.attributes.comment.website')}" %>

      </div>

        <div class='span2' style='text-align: center'>
          <%= image_tag avatar_url(current_user, 64), class: 'img-polaroid' %>
          <p><b><%= link_to current_user.full_name, user_path(current_user) %></b></p>
          <%= f.submit nil, :class => 'btn btn-primary' %>
        </div>

    <% else %>
      <div id='commenter-info', class='span6'>
        <%= image_tag avatar_url(current_user, 16), class: 'pull-right img-polaroid clearfix' %>
        <%= link_to current_user.full_name, user_path(current_user) %>

        <span class='pull-left'>
          <%= f.submit nil, :class => 'btn btn-primary' %>
        </span>
      </div>

      <%= f.input :name, readonly: true, as: :hidden,
        input_html: {value: current_user.full_name, class: "span5"} %>
      <%= f.input :email, readonly: true, as: :hidden,
        input_html: {value: current_user.email, class: "span5"} %>
      <%= f.input :website, readonly: true, as: :hidden,
        input_html: {value: current_user.website, class: "span5"} %>
      <%= f.input :user_id, as: :hidden,
        input_html: {value: current_user.id} %>
    <% end %>

  </div>
<% end %>
</div>

app/views/comments/_voting_buttons.html.erb
<% if turnoff_voting_button?(comment) %>
  <span class='btn btn-mini btn-success disabled'><%= comment.positive_votes_count.to_farsi %></span>
  <span class='btn btn-mini btn-danger disabled'><%= comment.negative_votes_count.to_farsi %></span>
<% else %>
  <button class="btn btn-mini btn-success btn-thumbs-up btn-comments-thumbs-up" data-id='<%= comment.id %>'><%= comment.positive_votes_count.to_farsi %></button>
  <button class="btn btn-mini btn-danger btn-thumbs-down btn-comments-thumbs-down" data-id='<%= comment.id %>'><%= comment.negative_votes_count.to_farsi %></button>
<% end %>

app/views/comments/edit.html.erb
<% set_meta_tags  title: [t('comments.title'), t('.title')],
                  noindex: true %>
<%- model_class = @comment.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.edit',model: model_class.model_name.human) %></h1>
<% end %>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<% set_meta_tags  title: [t('comments.title'), t('.title')],
                  noindex: true %>
<%- model_class = Comment.new.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:story_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @story.comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, story_comments_path(comment.story comment) %></td>
        <td><%= comment.name %></td>
        <td><%= comment.content %></td>
        <td><%= comment.story_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_story_comment_path(comment.story, comment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      story_comment_path(comment.story, comment),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_story_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<% set_meta_tags  title: [t('comments.title'), t('.title')],
                  noindex: true %>
<%- model_class = @comment.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
<% end %>
<% if params[:parent_id] %>
  <h3>درحال پاسخ به:</h3>
  <%= render @comment.parent if @comment.parent %>
  <br>
<% end %>

<%= render :partial => 'form' %>

app/views/comments/new.js.erb
$('.nested_comments .comment-form').remove()
$('#comment_<%= params[:parent_id] %>').next('.nested_comments').prepend('<%= j render 'form' %>')

app/views/comments/show.html.erb
<% set_meta_tags  title: [t('comments.title'), t('.title')],
                  description: "نمایش دیدگاه #{@comment.name}" %>
<%- model_class = @comment.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @comment.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @comment.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:story_id) %>:</strong></dt>
  <dd><%= @comment.story_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              story_comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_story_comment_path(@comment.story, @comment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              story_comment_path(@comment.story, @comment),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>