config/routes.rb
Nerdnews::Application.routes.draw do
  match "under_construction", :to => redirect('/')

  root :to => "stories#index"

  get "/faq" => "static_pages#faq", as: "static_pages_faq"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  match '/auth/:provider/callback' => 'identities#create'
  match '/auth/failure' => 'identities#failure'

  resources :identities, :only => [:index, :create, :destroy] do
    collection do
      get 'signup'
    end
  end

  resources :activity_logs
  resources :ratings
  resources :password_resets
  resources :pages
  resources :tags
  resources :mypage, only: :index
  resources :announcements do
    get :hide, on: :member
  end

  get "/login" => "sessions#new", as: "new_session"
  post "/login" => "sessions#create", as: "sessions"
  delete "/logout" => "sessions#destroy", as: "session"

  resources :users, path_names: { new: 'sign_up' } do
    get 'posts', on: :member
    get 'comments', on: :member
    get 'favorites', on: :member
    get 'activity_logs', on: :member
    post 'add_to_favorites', on: :member
    resources :messages, except: [:edit, :update, :show], path_names: { new: 'new' }
  end

  resources :stories do
    resources :votes, :defaults => { :voteable => 'stories' }
    resources :comments do
      resources :votes, :defaults => { :voteable => 'comments' }
    end
    get 'unpublished', :on => :collection
    put 'publish', :on => :member
    get 'recent', on: :collection
  end

  get "/:permalink" => "pages#show", as: "page_by_permalink"

  namespace :admin do
    get '', to: 'dashboard#index'
  end

end

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? 'success' : 'error' %> ">
    <a class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_head.html.erb
<head>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :head %>

  <% if Rails.env == "production" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35290892-12']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  <% end %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="content-language" content="fa" />

  <%= display_meta_tags :site => t('.title') %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
</head>

app/views/shared/_header.html.erb
<% unread_messages = current_user.count_unread_messages if current_user %>
<div class="navbar-inner">

  <div class="container">

    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <%= link_to root_path do %>
      <%= image_tag 'NerdLogo-58px.png', class: 'logo pull-right', title: t('.brand_name') %>
    <% end %>

    <!-- User Buttton -->
    <% unless current_user %>

    <div class="pull-left">
      <ul class="nav">
        <%= active_link_to t('.register'), new_user_path, active: [['users'], ['new', 'create']], :wrap_tag => :li %>
        <%= active_link_to t('.login'), new_session_path, active: [['sessions'], ['new', 'create']], :wrap_tag => :li %>
      </ul>
    </div>

    <% else %>
      <div class="btn-group pull-left">
        <a class="btn dropdown-toggle" data-toggle="dropdown" id="user-menu" href="<%= user_path(current_user) %>">
          <%= image_tag avatar_url(current_user) %>
          <%= truncate current_user.full_name, length: 16 %>
          <% if unread_messages > 0 %>
            <span class="label label-important"><%= unread_messages.to_farsi %></span>
          <% end %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">

          <li><%= link_to t('.profile'), user_path(current_user) %></li>

          <li class="divider"></li>

          <% if can? :index, ActivityLog %>
            <li><%= link_to t('.activity_logs'), activity_logs_path %></li>
          <% end %>

          <% if can? :unpublished, Story %>
            <li><%= link_to t('.unpublished_stories'), unpublished_stories_path %></li>
          <% end %>

          <% if can? :index, :mypage %>
            <li><%= link_to t('.mypage'), mypage_index_path %></li>
          <% end %>

          <li class="divider"></li>

          <% if can? :create, Tag %>
            <li><%= link_to t('.tags'), tags_path %></li>
          <% end %>

          <% if can? :index, User %>
            <li><%= link_to t('.users'), users_path %></li>
          <% end %>

          <% if can? :manage, Announcement %>
            <li><%= link_to t('.announcements'), announcements_path %></li>
          <% end %>

          <% if can? :index, Page %>
            <li><%= link_to t('.pages'), pages_path %></li>
          <% end %>

          <% if can? :create, Rating %>
            <li><%= link_to t('.ratings'), ratings_path %></li>
          <% end %>

          <% if can? :create, Message %>
            <li>
              <%= link_to user_messages_path(current_user) do %>
                <%= t('.messages') %>
                <% if unread_messages > 0 %>
                  <span class="label label-important">
                    <%= unread_messages.to_farsi %>
                  </span>
                <% end %>
              <% end %>
            </li>
          <% end %>

            <% if can? :index, Identity %>
              <li><%= link_to t('.identities'), identities_path %></li>
            <% end %>

            <li class="divider"></li>
          <li><%= link_to t('.logout'), session_path, method: :delete,
            data: {confirm: t("helpers.links.confirm")} %></li>
        </ul>
      </div>
    <% end %>

    <!-- Links -->
    <div class="nav-collapse">
      <ul class="nav">
        <%= active_link_to t('.home'), root_path, active: [['stories'], ['index']], :wrap_tag => :li %>

        <% if can? :index, :mypage %>
          <%= active_link_to t('.mypage'), mypage_index_path, active: [['mypage'], ['index']],
            :wrap_tag => :li %>
        <% end %>
        <%= active_link_to t('.new_story'), new_story_path, active: [['stories'], ['new', 'create']],
            :wrap_tag => :li %>
        <% if content_for?(:search) %>
          <%= yield :search %>
        <% else %>
          <%= form_tag stories_path, method: :get, class: "navbar-search pull-left" do %>
            <%= text_field_tag :search, params[:search], class: "span2 search-query",
              placeholder: t(".search") %>
          <% end %>
        <% end %>
      </ul>
      <!-- Social Icons -->
      <ul class='social-icons'>
        <li id="atom">
          <%= link_to stories_path + ".atom", format: "atom" do %>
            <%= image_tag 'social-icons/fc-webicon-rss-m.png' %>
          <% end %>
        </li>
        <li id="github">
          <%= link_to 'https://github.com/jnaqsh/nerdnews' do %>
            <%= image_tag 'social-icons/fc-webicon-github-m.png' %>
          <% end %>
        </li>
        <li id="googleplus">
          <%= link_to 'https://plus.google.com/b/111646924484501471492/111646924484501471492' do %>
            <%= image_tag 'social-icons/fc-webicon-googleplus-m.png' %>
          <% end %>
        </li>
        <li id="twitter">
          <%= link_to 'https://twitter.com/farsi_nerdnews' do %>
            <%= image_tag 'social-icons/fc-webicon-twitter-m.png' %>
          <% end %>
        </li>
        <li id="facebook">
          <%= link_to 'http://www.facebook.com/farsi.nerdnews' do %>
            <%= image_tag 'social-icons/fc-webicon-facebook-m.png' %>
          <% end %>
        </li>
        <li id="faq">
          <%= link_to static_pages_faq_path do %>
            <%= image_tag 'info_32.png' %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_loading_indicator.html.erb
<div id='loading-indicator' class='navbar-fixed-top'>
  <span><small>درحال بارگذاری...</span></small>
</div>