config/routes.rb
Nerdnews::Application.routes.draw do
  match "under_construction", :to => redirect('/')

  root :to => "stories#index"

  get "/faq" => "static_pages#faq", as: "static_pages_faq"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  match '/auth/:provider/callback' => 'identities#create'
  match '/auth/failure' => 'identities#failure'

  resources :identities, :only => [:index, :create, :destroy] do
    collection do
      get 'signup'
    end
  end

  resources :activity_logs
  resources :ratings
  resources :password_resets
  resources :pages
  resources :tags
  resources :mypage, only: :index
  resources :announcements do
    get :hide, on: :member
  end

  get "/login" => "sessions#new", as: "new_session"
  post "/login" => "sessions#create", as: "sessions"
  delete "/logout" => "sessions#destroy", as: "session"

  resources :users, path_names: { new: 'sign_up' } do
    get 'posts', on: :member
    get 'comments', on: :member
    get 'favorites', on: :member
    get 'activity_logs', on: :member
    post 'add_to_favorites', on: :member
    resources :messages, except: [:edit, :update, :show], path_names: { new: 'new' }
  end

  resources :stories do
    resources :votes, :defaults => { :voteable => 'stories' }
    resources :comments do
      resources :votes, :defaults => { :voteable => 'comments' }
    end
    get 'unpublished', :on => :collection
    put 'publish', :on => :member
    get 'recent', on: :collection
  end

  get "/:permalink" => "pages#show", as: "page_by_permalink"

  namespace :admin do
    get '', to: 'dashboard#index'
  end

end

app/models/story.rb
#encoding: utf-8

class Story < ActiveRecord::Base
  acts_as_paranoid
  acts_as_textcaptcha

  HIDE_THRESHOLD = -8

  attr_accessible :content, :publish_date, :title, :source,
    :tag_names, :view_counter, :publisher_id, :tag_ids

  extend FriendlyId
  friendly_id :title_foo, use: [:slugged, :history]

  def title_foo
    "#{title}"
  end

  def normalize_friendly_id(string)
    sep = "-"
    parameterized_string = string
    parameterized_string.gsub!(/[^a-z0-9\-_اآبپتثجچحخدذرزژسشصضطظعغفقکگلمنوهیءئؤيإأةك۱۲۳۴۵۶۷۸۹۰ٔ‌]+/i, sep)
    unless sep.nil? || sep.empty?
      re_sep = Regexp.escape(sep)
      # No more than one of the separator in a row.
      parameterized_string.gsub!(/#{re_sep}{2,}/, sep)
      # Remove leading/trailing separator.
      parameterized_string.gsub!(/^#{re_sep}|#{re_sep}$/i, '')
    end
    parameterized_string.downcase
  end

  belongs_to :remover, class_name: "User"
  belongs_to :publisher, class_name: "User"
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, :through => :taggings,
                  :after_add => :calculate_count,
                  :after_remove => :calculate_count
  has_many :votes, as: :voteable
  belongs_to :user, counter_cache: true

  scope :not_approved, where(:publish_date => nil)
  scope :approved, where("publish_date", present?)

  before_validation :smart_add_url_protocol

  validates_length_of :title, maximum: 100, minimum: 10
  validates_length_of :content, minimum: 250, maximum: 1500
  validates  :title, :content, presence: true
  validates :source, allow_blank: true, uri: true

  attr_reader :tag_names

  searchable do
    integer :id
    text :title, boost: 5
    text :content
    text :comments do
      comments.map(&:content)
    end
    time :publish_date
    time :created_at
    boolean :hide
    text :user do
      user.full_name if user.present?
      user.email if user.present?
    end
    text :tags do
      tags.map(&:name)
    end
  end

  def published?
    publish_date.present? ? true : false
  end

  def perform_textcaptcha?
    !skip_textcaptcha
  end

  def tag_names=(tokens)
    # self.tag_ids = Tag.ids_from_tokens(tokens)
    tags_array = tokens.split(",")
    self.tags.clear
    tags_array.each do |tag|
      found_tag = Tag.find_by_name(tag.strip)
      if !found_tag.blank?
        self.tags << found_tag if !self.tags.include?(found_tag)
      else
        self.tags << Tag.create!(name: tag.strip) if tag.strip.size != 0
      end
    end
  end

  def mark_as_published(user, url)
    self.update_attributes({publish_date: Time.zone.now, publisher: user}, without_protection: true)
    # conditional due to error on request user spec
    Rails.env.production? ? Tweet.tweet(Twitter::Client.new, "#{self.title}", url) : true
  end

  def user_voted?(user)
    !self.votes.where("user_id = ?", user).blank?
  end

  def approved?
    self.publish_date.present?
  end

protected
  # Searches through recent stories and mark them to hide if
  # too much negative rating is submitted for them
  def self.hide_negative_stories
    recent_stories = where(publish_date: (Time.zone.now.midnight - 1.day)..Time.zone.now.midnight)
    recent_stories.each do |rs|
      rs.update_attribute :hide, true if rs.total_point < Story::HIDE_THRESHOLD
      rs.index!
    end
  end

private
  def calculate_count(tag)
    tag.update_attribute :stories_count, tag.stories.count
  end

  def smart_add_url_protocol
    if self.source.present?
      unless self.source[/^https?:\/\//]
        self.source = 'http://' + self.source
      end
    end
  end
end

app/controllers/stories_controller.rb
# encoding: utf-8

class StoriesController < ApplicationController
  load_and_authorize_resource
  # GET /stories
  # GET /stories.json

  def recent
    @stories = Story.approved.where('publish_date > ? and hide = ?', Time.at(params[:after].to_f), false).order("publish_date desc")

    respond_to do |format|
      format.js
    end
  end

  def index
    @stories = Story.search(:include => [:tags, :user, :publisher, {:votes => [:rating, :user]}]) do
      without(:publish_date, nil)
      without(:hide, true)
      fulltext params[:search]
      fulltext params[:tag]
      order_by :publish_date, :desc
      paginate :page => params[:page], :per_page => 20
    end.results

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.atom
      format.json { render json: @stories }
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @story = Story.includes([:tags, :user, :publisher, {:votes => [:rating, :user]}]).find(params[:id])

    if @story
      @story.increment!(:view_counter)
      @comment = @story.comments.build
      @comments = @story.comments.approved.includes(:user, :story).arrange(order: :created_at)

      story_path = Rails.env.production? ? story_path(@story).downcase : story_path(@story) #monkey patch due to error in production (downcase)

      if request.path != story_path
        redirect_to @story, status: :moved_permanently, only_path: true
        return
      end
    else
      raise ActiveRecord::RecordNotFound, t("controllers.stories.show.story_not_found")
    end

    respond_to do |format|
      format.html
    end
  end

  # GET /stories/new
  # GET /stories/new.json
  def new
    @story = Story.new
    @story.textcaptcha

    bypass_captcha_or_not @story

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @story }
    end
  end

  # GET /stories/1/edit
  def edit
    @story = Story.find(params[:id])
  end

  # POST /stories
  # POST /stories.json
  def create
    if current_user
      @user = current_user
      @story = @user.stories.build(params[:story])
    else
      @story = Story.new(params[:story])
    end

    bypass_captcha_or_not @story

    respond_to do |format|
      if params[:preview_button]
        format.html { render action: "new" }
      else
        if @story.save

          record_activity %Q(خبر #{view_context.link_to @story.title.truncate(40), story_path(@story)} را ایجاد کرد)

          format.html { redirect_to root_path, only_path: true,
            notice: t("controllers.stories.create.flash.success", link: unpublished_stories_path).html_safe }
          format.json { render json: @story, status: :created, location: @story }
        else
          format.html { render action: "new" }
          format.json { render json: @story.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PUT /stories/1
  # PUT /stories/1.json
  def update
    @story = Story.find(params[:id])
    @story.attributes = params[:story]

    respond_to do |format|
      if params[:preview_button]
        format.html { render action: "edit" }
      else
        if @story.update_attributes(params[:story])

          record_activity %Q(خبر #{view_context.link_to @story.title.truncate(40), story_path(@story)} را ویرایش کرد)

          if @story.published?
            format.html { redirect_to @story, notice: t('controllers.stories.update.flash.success') }
          else
            format.html { redirect_to unpublished_stories_path, notice: t('controllers.stories.update.flash.success') }
          end

          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @story.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story = Story.find(params[:id])
    @story.destroy

    @story.update_attributes({remover: current_user}, without_protection: true)

    record_activity %Q(خبر #{view_context.link_to @story.title.truncate(40), story_path(@story)} را حذف کرد)

    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  # PUT /stories/1/publish
  def publish
    @story = Story.find(params[:id])

    respond_to do |format|
      if @story.mark_as_published(current_user, story_url(@story))

        rate_user(@story.user, 3) if @story.user #rate for user who wrote a story
        rate_user(1) if current_user #rate for user who publish a story

        record_activity %Q(خبر #{view_context.link_to @story.title.truncate(40), story_path(@story)} را منتشر کرد)

        format.html { redirect_to story_path(@story),
          notice: t('controllers.stories.publish.flash.success') }
      end
    end
  end

  # GET /stories/list
  def unpublished
    @stories = Story.not_approved.includes([:tags, :user, {:votes => [:rating, :user]}]).order("created_at DESC").page params[:page]

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def turnoff_voting_button?(story)
    if cookies[:votes].present?
      cookie_array = YAML.load cookies[:votes]
      cookie_array.include? story.id
    elsif current_user
      story.user_voted?(current_user)
    end
  end

  def thumbnail_url(story)
    unless story.tags.first.nil?
#      "#{root_url.gsub(/\/$/, '') + story.tags.first.thumbnail.url}"
      story.tags.first.thumbnail.url #using dropbox in production
    end
  end

  def hide_story?(story)
    if story.total_point < Story::HIDE_THRESHOLD
      if current_page?(controller: "stories", action: "index") or
        current_page?(controller: "mypage", action: "index") or
        current_page?("/stories")
          return true
      end
    end
    return false
  end

  def positive_or_negative(vote)
    if vote.rating.weight >= 0
      "label-success"
    else
      "label-important"
    end
  end
end

app/views/stories/_form.html.erb
<%= simple_form_for @story, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title,
              input_html: {class: "span6"},
              placeholder: t('.title_placeholder')
              %>
  <%= f.input :source,
              input_html: {class: "span6"},
              placeholder: t('.source_placeholder')
              %>
  <%= f.input :content,
              input_html: {rows: 15, class: "span6", 'data-trigger' => "focus"},
              placeholder: t('.content_placeholder')%>

  <%= f.input :tag_names, input_html: {data: {tags: @story.tags}, class: "span6", value: ' '} %>

  <%#= f.association :tags, collection: [], input_html: {data: {tags: @story.tags}, class: "span6", multiple: ' '} %>

  <%= textcaptcha_fields(f) do %>
    <%= f.input :spam_answer, placeholder: @story.spam_question,
              input_html: {class: "span6"} %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= f.submit t('.preview', :default => t("helpers.links.preview")), :class => 'btn btn-primary', name: "preview_button" %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                stories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/stories/_preview_story.html.erb
<div class='preview'>
  <div class='alert'>
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>هشدار</strong> این یک پیش‌نمایش است. خبر شما هنوز ثبت نشده است.
  </div>

  <%= render preview_story %>
</div>

app/views/stories/_sidebar.html.erb
<!-- sidebar -->
<h3>راهنما</h3>
<p>
   ساخت پیوند: "پیوند":http://link <br /.>
   درشت کردن: *<b>متن درشت</b>* <br />
   مورب کردن: _<i>متن مورب</i>_
</p>

app/views/stories/_social_share.html.erb
<ul class='social-icons'>
  <li>
    <a href="http://www.facebook.com/sharer.php?u=<%= share_url %>&t=<%= title %>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="icon-facebook-sign"></i></a>
  </li>
  <li>
    <a href="http://twitter.com/home?status=<%= title + " " + share_url %>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="icon-twitter-sign"></i></a>
  </li>
  <li>
    <a href="https://m.google.com/app/plus/x/?v=compose&content=<%= title %>&url=<%= share_url %>" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><i class="icon-google-plus-sign"></i></a>
  </li>
</ul>

app/views/stories/_story.html.erb
<!-- cache status of Story -->
<% status = hide_story?(story) %>

<%= content_tag :article, class: "story #{'grey-out' if status}",
      data: {timestamp: story.publish_date.to_f} do %>
  <div class='row'>
    <div class='span1 visible-desktop'>
      <div class='story-image'>
      <% unless story.tags.blank? %>
        <%= link_to image_tag(story.tags.first.thumbnail.url(:thumb), class: 'img-polaroid'), stories_url(tag: story.tags.first.name) %>
      <% end %>
      </div>
      <% unless status %>
        <ul class="tags">
          <% story.tags.each do |tag| %>
          <% favored = true if current_user and current_user.included_tag_as_favorite?(tag.name) %>
            <%= content_tag :li, rel: "tooltip", title: tag.name do %>
              <p>
                <%= link_to stories_url(tag: tag.name) do %>
                  <%= truncate(tag.name, length: 8) %>
                <% end %>
                <span class="tag_id_<%= tag.id %> <%= 'yellow' if favored %>">
                  <% if current_user && !favored %>
                    <%= link_to add_to_favorites_user_path(id: current_user, tag: tag.name), class: "#{'yellow' if favored}", method: :post, remote: true do %>
                      <i class='icon-star'>1</i>
                    <% end %>
                  <% end %>
                </span>
              </p>
            <% end %>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class='span11'>

      <h3><%= link_to story.title, story %></h3>

      <% if story.published? %>
        <% unless status or params[:preview_button] %>
          <%= render partial: 'stories/social_share', locals: {title: story.title, share_url: story_url(story)} %>
        <% end %>
      <% end %>

      <h5 class="muted">

        <small>
          <span>
            <i class='icon-plus' title="امتیاز"></i>
            <%= t('stories.index.point') + story.total_point.to_farsi %>
          </span>

          <span>
            <i class='icon-eye-open' title="تعداد نمایش"></i>
            <%= t('stories.index.views_count') + story.view_counter.to_farsi %>
          </span>

          <span>
            <i class='icon-user' title="نویسنده"></i>
            <%= user_name(story) %>
          </span>

          <span>
            <i class='icon-calendar' title="تاریخ انتشار"></i>
            <%= to_jalali(story.publish_date) if story.approved? %>
          </span>

          <% if story.id %>
            <span>
              <i class='icon-comments-alt' title="تعداد دیدگاه‌ها"></i>
              <%= link_to story_path(story) do %>
                <%=t 'stories.show.comments' %>
                <%= story.comments_count.to_farsi %>
              <% end %>
            </span>
          <% end %>

          <% if story.published? %>
            <span>
              <i class='icon-ok' title="تاییدکننده"></i>
              <%= link_to story.publisher.full_name, user_path(story.publisher) %>
            </span>
          <% end %>

          <% if (can? :create, Vote) && story.votes.any? %>
            <span>
              <i class='icon-thumbs-up' title="رای‌دهندگان"></i>
              <%= link_to t('.voters'), "#", class: "toggle-voters" %>
            </span>
          <% end %>
        </small>
      </h5>

      <%= render partial: "stories/voters", locals: {story: story} %>

      <% unless status %>
        <p><%= user_name(story) %> می‌نویسد:</p>
        <blockquote>
          <%= sanitize(RedCloth.new(story.content, [:filter_html, :filter_styles]).to_html) %><br />
          <%= source_of_story(story) %>
        </blockquote>
      <% end %>

      <%= render partial: "stories/story_operation", locals: {story: story} %>
    </div>
  </div>
<% end %>
<hr />

app/views/stories/_story_operation.html.erb
<% if story.id && !params[:preview_button] %>
  <div class='row'>
    <% if can? :create, Vote %>
      <div id='voting-buttons-<%= story.id %>' class='span1 btn-group pull-right' >

        <%= render 'stories/voting_buttons', story: story %>

      </div>
      <div class='span5 thumbs-up-list' id='thumbs-up-list-<%= story.id %>'>
        <ul>
          <% Rating.positive('stories').each do |rating| %>
            <li class='icon-hand-left'>
              <%= link_to rating.name, story_votes_path(story, rating_id: rating, positive: true),
                method: :post, remote: true %>
            </li>
          <% end %>
        </ul>
      </div>
      <div class='span5 thumbs-down-list' id='thumbs-down-list-<%= story.id %>'>
        <ul>
          <% Rating.negative('stories').each do |rating| %>
            <li class='icon-hand-left'>
              <%= link_to rating.name, story_votes_path(story, rating_id: rating), method: :post, remote: true %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class='pull-left'>
      <% if (can? :update, story) && (!story.published? or current_user.role? "founder") %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_story_path(story), :class => 'btn btn-mini' %>
      <% end %>
      <% if (can? :destroy, story) && (!story.published? or current_user.role? "founder") %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      story_path(story),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger'
                       %>
      <% end %>
      <% if (can? :publish, story) && !story.published? %>
        <%= link_to t('.publish', default: t('helpers.links.publish')), publish_story_path(story),
            class: "btn btn-mini btn-primary", method: :put %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/stories/_voters.html.erb
<% if story.id && !params[:preview_button] %>
  <div class='row voters' style="display: none">
    <% if can? :create, Vote %>
      <div class="well span10">
        <% story.votes.each do |vote| %>
          <%= content_tag :span, class: "label #{positive_or_negative(vote)}" do %>
            <%= link_to vote.user.full_name, user_path(vote.user), title: vote.rating.name, rel: "tooltip" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/stories/_voting_buttons.html.erb
<% if turnoff_voting_button?(story) %>
  <span class='btn btn-success disabled'>
    <%= story.positive_votes_count.to_farsi %>
    <i class='icon-thumbs-up'></i>
  </span>
  <span class='btn btn-danger disabled'>
    <i class='icon-thumbs-down'></i>
    <%= story.negative_votes_count.to_farsi %>
  </span>
<% else %>
  <button class="btn btn-success btn-thumbs-up" data-id='<%= story.id %>'><%= story.positive_votes_count.to_farsi %> <i class='icon-thumbs-up'></i></button>
  <button class="btn btn-danger btn-thumbs-down" data-id='<%= story.id %>'><i class='icon-thumbs-down'></i> <%= story.negative_votes_count.to_farsi %></button>
<% end %>

app/views/stories/edit.html.erb
<% set_meta_tags  title: [t('stories.title'), t('.title')],
                  noindex: true %>
<%- model_class = @story.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
<% end %>

<% if params[:preview_button] %>
  <%= render partial: "preview_story", object: @story %>
<% end %>

<div class="row">
   <!-- main content -->
   <div class="span9">
      <%= render :partial => 'form' %>
   </div>
   <div class="span3">
      <%= render 'sidebar' %>
   </div>
</div>

app/views/stories/index.html.erb
<% set_meta_tags title: [t('stories.title'), t('.title')],
                 description: 'یک شبکهٔ اجتماعی خبر برای افراد نرد و گیک که علاقه به اخبار فناوری دارند. در این شبکه همه افراد می‌توانند خبر بنویسند و محدودیتی وجود ندارد. هر خبر دارای امتیازی است که خبرهای امتیاز پایین جایگاه خوبی در این شبکه ندارند.',
                 keywords: 'اخبار, صفحه اصلی, فناوری,گیک,خوره,نرد,نردنیوز,شبکه اجتماعی خبر',
                 canonical: root_url %>

<%- model_class = Story.new.class -%>
<% content_for :head, auto_discovery_link_tag(:atom, stories_url(:format => "atom")) %>
<% content_for :page_header do %>
    <h1>
      <%=t '.title', :default => model_class.model_name.human.pluralize %>
      <% if can? :create, Story %>
        <%= link_to t('.new', :default => t("helpers.links.new")),
                  new_story_path,
                  :class => 'hidden-phone btn btn-large btn-success pull-left' %>
      <% end %>
    </h1>
<% end %>

<div class="alert alert-info" id="show_stories" style="display: none">
  خبرهای جدیدی منتشر گردیده‌است - <a href="#">کلیک کنید تا آن‌ها را ببینید</a>
</div>

<%= content_tag :div, id: "stories", data: {url: recent_stories_url(format: :js)} do %>
  <%= (render @stories) || "خبر مورد نظر پیدا نشد" %>
<% end %>

<%= paginate @stories %>

app/views/stories/index.js.erb
$('#stories').append('<%= j render(@stories) %>');
<% if @stories.next_page %>
  $(".pagination").replaceWith('<%= j paginate(@stories) %>');
<% else %>
  $('.pagination').remove();
<% end %>

<% sleep 1 %>

$("[rel=tooltip]").tooltip()

app/views/stories/new.html.erb
<% set_meta_tags title: [t('stories.title'), t('.title')],
                 description: 'ارسال خبر جدید',
                 keywords: 'ارسال خبر',
                 canonical: new_story_url %>

<%- model_class = @story.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
<% end %>

<% if params[:preview_button] %>
  <%= render partial: "preview_story", object: @story %>
<% end %>

<div class="row">
   <!-- main content -->
   <div class="span9">
      <%= render :partial => 'form' %>
   </div>
   <div class="span3">
      <%= render 'sidebar' %>
   </div>
</div>

app/views/stories/show.html.erb
<% set_meta_tags title: [t('stories.title'), @story.title],
                 description: sanitize(RedCloth.new(@story.content, [:filter_html, :filter_styles]).to_plain).truncate(160),
                 keywords: @story.tags.map { |tag| tag.name },
                 canonical: story_url(@story),
                 open_graph: {
                    title: "#{@story.title}",
                    type: 'news',
                    url: "#{story_url(@story)}",
                    image: thumbnail_url(@story) } %>

<%- model_class = @story.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
<% end %>

<%= render @story %>

<div class="comments span8 offset2">

  <% if can? :create, Comment %>
    <%= render "comments/form" %>
  <% end %>

  <div id='comments-container'>
    <h2><%= t('.comments') %></h2>
    <%= (nested_comments @comments) || t('.no_comments') %>
  </div>
</div>

app/views/stories/unpublished.html.erb
<% set_meta_tags  title: [t('stories.title'), t('.title')],
                  noindex: true %>
<%- model_class = Story.new.class -%>
<% content_for :page_header do %>
  <h1>
    <%=t '.title', :default => model_class.model_name.human.pluralize %>
  </h1>
<% end %>

<%= render partial: "story", collection: @stories %>

<%= paginate @stories %>