config/routes.rb
Nerdnews::Application.routes.draw do
  match "under_construction", :to => redirect('/')

  root :to => "stories#index"

  get "/faq" => "static_pages#faq", as: "static_pages_faq"

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  match '/auth/:provider/callback' => 'identities#create'
  match '/auth/failure' => 'identities#failure'

  resources :identities, :only => [:index, :create, :destroy] do
    collection do
      get 'signup'
    end
  end

  resources :activity_logs
  resources :ratings
  resources :password_resets
  resources :pages
  resources :tags
  resources :mypage, only: :index
  resources :announcements do
    get :hide, on: :member
  end

  get "/login" => "sessions#new", as: "new_session"
  post "/login" => "sessions#create", as: "sessions"
  delete "/logout" => "sessions#destroy", as: "session"

  resources :users, path_names: { new: 'sign_up' } do
    get 'posts', on: :member
    get 'comments', on: :member
    get 'favorites', on: :member
    get 'activity_logs', on: :member
    post 'add_to_favorites', on: :member
    resources :messages, except: [:edit, :update, :show], path_names: { new: 'new' }
  end

  resources :stories do
    resources :votes, :defaults => { :voteable => 'stories' }
    resources :comments do
      resources :votes, :defaults => { :voteable => 'comments' }
    end
    get 'unpublished', :on => :collection
    put 'publish', :on => :member
    get 'recent', on: :collection
  end

  get "/:permalink" => "pages#show", as: "page_by_permalink"

  namespace :admin do
    get '', to: 'dashboard#index'
  end

end

app/models/tag.rb
#encoding: utf-8

class Tag < ActiveRecord::Base
  attr_accessible :name, :thumbnail

  has_attached_file :thumbnail, :styles => { thumb: "64x64#" }, :default_url => "missing_64.png"

  has_many :taggings, dependent: :destroy
  has_many :stories, :through => :taggings

  validates :name, uniqueness: true, presence: true
  # We can't validate presence of thumbnail, because regular users
  # who posts stories can't assgine thumbnail for it
  validates_attachment :thumbnail,
    :content_type => {:content_type => ['image/jpeg', 'image/jpg', 'image/png']},
    :size => { :in => 0..100.kilobytes }

  searchable do
    text :name, as: "name_textp"
    text :id
    time :created_at
  end

  # private

  #   def self.tokens(query)
  #     tags = where("name like ?", "%#{query}%").select(:id, :name)
  #   end

  #   def self.ids_from_tokens(tokens)
  #     tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
  #     tokens.split(',')
  #   end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  load_and_authorize_resource

  def index
    @tags = Tag.search do
      fulltext params[:tag_search]
      order_by :created_at, :desc
      paginate :page => params[:page], :per_page => 100
    end.results

    respond_to do |format|
      format.html
      format.json {render json: @tags}
      format.js
    end
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: t('controllers.tags.create.flash.success') }
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_path }
    end
  end

  def edit
  end

  def update

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to tags_path, notice: t('controllers.tags.update.flash.success') }
      else
        format.html { render action: 'edit' }
      end
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= simple_form_for @tag, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <%= f.input :name,
              input_html: {class: "span6"} %>
  <div class='control-group'>
    <% unless @tag.new_record? || @tag.errors.any? %>
      <%= image_tag @tag.thumbnail.url(:thumb), class: 'img-polaroid pull-left' %>
    <% end %>
    <%= f.label :thumbnail, label: t("activerecord.attributes.tag.thumbnail"), class: 'control-label' %>
    <div class='controls'>
      <%= f.file_field :thumbnail %>
      <%= f.error :thumbnail_file_size %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tags_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<li class="span2">
  <div class="thumbnail">
    <%= image_tag tag.thumbnail.url(:thumb), alt: tag.name %>
    <h4><%= link_to tag.name.truncate(11), stories_path(tag: tag.name) %></h4>

    <% if (can? :edit, Tag) or (can? :destroy, Tag) %>
    <p>
      <% if can? :edit, Tag %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_tag_path(tag), :class => 'btn btn-mini' %>
      <% end %>

      <% if can? :destroy, Tag %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  tag_path(tag),
                  :method => :delete,
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                  :class => 'btn btn-mini btn-danger' %>
      <% end %>
    </p>
    <% end %>
  </div>
</li>

app/views/tags/edit.html.erb
<% set_meta_tags  title: [t('tags.title'), t('.title')],
                  noindex: true %>
<%- model_class = @tag.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}") %></h1>
<% end %>
<%= render :partial => 'form' %>

app/views/tags/index.html.erb
<% set_meta_tags  title: [t('tags.title'), t('.title')],
                  description: 'تگ‌ها' %>
<%- model_class = Tag.new.class -%>
<% content_for :page_header do %>
    <h1>
      <%=t '.title', default: model_class.model_name.human %>
      <% if can? :create, Tag %>
        <%= link_to t('.new', :default => t("helpers.links.new")), new_tag_path,
          class: 'btn btn-large btn-success pull-left' %>
      <% end %>
    </h1>
<% end %>

<div class = 'row'>
  <div class='span2'>
    <%= form_tag tags_path, remote: true, method: :get, class: 'form-search' do %>
      <div class='row'>
        <%= text_field_tag :tag_search, params[:tag_search], class: "span2 search-query", placeholder: t(".search") %>
      </div>
    <% end %>
  </div>
</div>

<div class='row'>
  <div class='span12'>
    <ul class="thumbnails" id="tags-list">
      <%= render(@tags) %>
    </ul>
    <%= paginate @tags %>
  </div>
</div>

app/views/tags/index.js.erb
<% if params[:tag_search] %>
  $('#tags-list').html('<%= j render(@tags) %>');
<% else %>
  $('#tags-list').append('<%= j render(@tags) %>');
<% end %>

<% if @tags.next_page %>
  $(".pagination").replaceWith('<%= j paginate(@tags) %>');
<% else %>
  $('.pagination').remove();
<% end %>

<% sleep 1 %>

$("[rel=tooltip]").tooltip()

app/views/tags/new.html.erb
<% set_meta_tags  title: [t('tags.title'), t('.title')],
                  noindex: true %>
<%- model_class = @tag.class -%>
<% content_for :page_header do %>
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
<% end %>
<%= render :partial => 'form' %>